### ISSUE TITLE
Mute and unmute endpoints

### ISSUE THREAD

**Issue by KennethHoff** [sen87/jack_mixer_cc#2]
Would you be willing to add a `mute` and `unmute` endpoint, as opposed to just a `toggle mute`? Say just `--mute` and `--unmute`?

**Comment by sen87** [comment]
Hi Kenneth,

sure no problem. I have added dedicated (un-)mute controls with the following new parameters:

-m <chan name>          mute
-u <chan name>           unmute
-t <chan name>            toggle mute

greetings,
sen

**Comment by KennethHoff** [comment]
Thank you for implementing it so quickly! I'll try this later today :)
